#pragma once

#include "NativeGameplayTags.h"

namespace Knowledge
{
	namespace Fragment
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Image);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Text);
	}
	namespace Category
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symbol);
	}
	namespace Symbol
	{
		namespace Numeric
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zero);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(One);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Two);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Three);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Four);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Five);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Six);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Seven);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Eight);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nine);
		}
	}
	namespace Hieroglyphic
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Apostrophe_1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Apostrophe_2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(B);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(D);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(G);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(H);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HLong);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(K);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(M);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(N);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(P);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(S);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SShort);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SLong);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(T);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TLong);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(W);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Y);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Z);
	}
}