#pragma once

#include "NativeGameplayTags.h"

namespace Fragment
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grid);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Icon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stack);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Consumable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemName);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PrimaryAttribute);
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ItemType);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlavorText);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SellValue);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RequiredLevel);

	namespace AttributeModifier
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeModifier_1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeModifier_2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttributeModifier_3);
	}
}
