#pragma once

#include "NativeGameplayTags.h"

namespace Puzzle
{
	namespace Box
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(True);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Safe);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blue);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gold);
	}
	namespace Numeric
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zero);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(One);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Two);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Three);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Four);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Five);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Six);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Seven);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Eight);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nine);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enter);
	}
}