#pragma once

#include "NativeGameplayTags.h"

namespace Puzzle
{	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hieroglyphics);
	
	namespace Box
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(True);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Safe);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Blue);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Red);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gold);
	}
	namespace Numeric
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zero);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(One);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Two);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Three);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Four);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Five);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Six);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Seven);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Eight);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Nine);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enter);
	}

	namespace Breakable
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(True);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(False);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pattern);
	}
	namespace Hieroglyphic
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Apostrophe_1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Apostrophe_2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(B);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(D);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(G);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(H);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HLong);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(K);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(M);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(N);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(P);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Q);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(S);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SShort);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SLong);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(T);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TLong);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(W);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Y);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Z);
	}
}